Repository hmcts/ccd-case-disposer, pull requests merged in 2021-11, with the labels that each got.

#7 RDM-12839 Add DELETE_CASE_TYPES
  charts/ccd-case-disposer/Chart.yaml
  charts/ccd-case-disposer/values.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/ApplicationParametersIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/dao/CaseDataRepositoryIntegrationTest.java
  src/integrationTest/resources/application-test.yaml
  src/main/java/uk/gov/hmcts/reform/ccd/ApplicationParameters.java
  src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionServiceTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-7

#6 CCD-2117: Address CVE-2021-42340
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-6

#8 CCD-2134: Address CVE-2021-22096
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-8

#11 RDM-12935 - SPIKE to implement functional tests
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/CaseDeletionServiceFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/config/TestApplicationConfiguration.java
  src/functionalTest/resources/application-functional.yaml
  src/functionalTest/resources/test_data.sql
  src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionService.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-11

#10 Feature/rdm 12886 delete linked cases
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/CaseDeletionServiceFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/config/TestApplicationConfiguration.java
  src/functionalTest/resources/application-functional.yaml
  src/functionalTest/resources/test_data.sql
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/ApplicationParametersIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/dao/CaseDataRepositoryIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/dao/CaseEventRepositoryIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/dao/CaseLinkRepositoryIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/es/CaseDataElasticsearchOperationsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/es/TestElasticsearchFixture.java
  src/integrationTest/resources/application-test.yaml
  src/integrationTest/resources/sql/data/case-events.sql
  src/integrationTest/resources/sql/data/create-cases.sql
  src/integrationTest/resources/sql/schema/.keep
  src/main/java/uk/gov/hmcts/reform/ccd/ApplicationExecutor.java
  src/main/java/uk/gov/hmcts/reform/ccd/ApplicationParameters.java
  src/main/java/uk/gov/hmcts/reform/ccd/data/dao/CaseLinkRepository.java
  src/main/java/uk/gov/hmcts/reform/ccd/data/entity/CaseLinkEntity.java
  src/main/java/uk/gov/hmcts/reform/ccd/data/entity/CaseLinkPrimaryKey.java
  src/main/java/uk/gov/hmcts/reform/ccd/data/es/CaseDataElasticsearchOperations.java
  src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionService.java
  src/main/java/uk/gov/hmcts/reform/ccd/service/CaseFinderService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/ccd/ApplicationExecutorTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/data/es/CaseDataElasticsearchOperationsTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/fixture/CaseLinkEntityBuilder.java
  src/test/java/uk/gov/hmcts/reform/ccd/fixture/TestData.java
  src/test/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/service/CaseFinderServiceTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-10

#9 Update Jenkinsfile_CNP sync branches
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-9

#12 CCD-2189: Upgrade elasticsearch client version to address CVEs
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-12
