Repository hmcts/ccd-case-disposer, pull requests merged in 2021-12, with the labels that each got.

#16 update log4j
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-16

#17 CCD-2351: Update log4j version to 2.16.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-17

#18 CCD-2374: Update log4j version to 2.17.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-18
