Repository hmcts/ccd-case-disposer, pull requests merged in 2022-04, with the labels that each got.

#29 --Adding the Suppression for Spring Beans jar. Temporary fix.
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-29

#28 spring framework versiyon update to 5.3.18 from 5.3.15
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-28

#32 LAU-327 Upgrade Elastic Search Client
  build.gradle
  charts/ccd-case-disposer/values.preview.template.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/es/CaseDataElasticsearchOperationsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/es/TestElasticsearchFixture.java
  src/main/java/uk/gov/hmcts/reform/ccd/data/es/CaseDataElasticsearchOperations.java
  src/test/java/uk/gov/hmcts/reform/ccd/data/es/CaseDataElasticsearchOperationsTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-32

#30 LAU-347 Update Case Deletion process to include additional parameter …
  build.gradle
  charts/ccd-case-disposer/Chart.yaml
  charts/ccd-case-disposer/values.preview.template.yaml
  charts/ccd-case-disposer/values.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/CaseDeletionFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/TestDataProvider.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/parameter/TestParameterResolver.java
  src/functionalTest/resources/application-functional.yaml
  src/functionalTest/resources/scenarios/S-019-simulated-case-type.sql
  src/functionalTest/resources/scenarios/S-020-simulated-and-deletable-case-types.sql
  src/functionalTest/resources/scenarios/S-021-mix-bag-of-deletable-and-simulated-cases.sql
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/es/TestElasticsearchFixture.java
  src/integrationTest/resources/application-test.yaml
  src/main/java/uk/gov/hmcts/reform/ccd/ApplicationExecutor.java
  src/main/java/uk/gov/hmcts/reform/ccd/data/model/CaseDataView.java
  src/main/java/uk/gov/hmcts/reform/ccd/exception/DuplicateCaseTypeException.java
  src/main/java/uk/gov/hmcts/reform/ccd/parameter/DefaultParameterResolver.java
  src/main/java/uk/gov/hmcts/reform/ccd/parameter/DeletableCaseTypePropertyInterceptor.java
  src/main/java/uk/gov/hmcts/reform/ccd/parameter/ParameterResolver.java
  src/main/java/uk/gov/hmcts/reform/ccd/policy/CaseTypeRetentionPolicyImpl.java
  src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionResolver.java
  src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionSimulationService.java
  src/main/java/uk/gov/hmcts/reform/ccd/service/CaseFamilyTreeService.java
  src/main/java/uk/gov/hmcts/reform/ccd/util/LogConstants.java
  src/main/java/uk/gov/hmcts/reform/ccd/util/log/CaseDataViewBuilder.java
  src/main/java/uk/gov/hmcts/reform/ccd/util/log/CaseDataViewHolder.java
  src/main/java/uk/gov/hmcts/reform/ccd/util/log/CaseFamiliesFilter.java
  src/main/java/uk/gov/hmcts/reform/ccd/util/log/TableTextBuilder.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/ccd/ApplicationExecutorTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/fixture/TestData.java
  src/test/java/uk/gov/hmcts/reform/ccd/parameter/DeletableCaseTypePropertyInterceptorTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/policy/CaseTypeRetentionPolicyImplTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionResolverTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionSimulationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/service/CaseFamilyTreeServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/service/CaseFinderServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/util/log/CaseDataViewBuilderTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/util/log/CaseDataViewHolderTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/util/log/CaseFamiliesFilterTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/util/log/TableTextBuilderTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-30

#37 New Dates
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-37

#38 Spring-core-5.3.18.jar dependency issue suppression
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-38
