Repository hmcts/ccd-case-disposer, pull requests merged in 2022-11, with the labels that each got.

#143 CCD-3802 Update to fortify-client version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-143

#148 LAU-548 update ccd to version 8
  charts/ccd-case-disposer/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-148

#149 LAU-548 remove suppression related to snake
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-149

#151 LAU-548 gradle upgrade 7.4.2
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-151

#140 CCD-3773 Conditionally cleanup helm releases on PRs
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-140

#157 Add await in DatabaseTestUtils
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/utils/DatabaseTestUtils.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-157

#156 LAU-558 Refactor case disposer remote operations
  charts/ccd-case-disposer/Chart.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/ApplicationBootstrapIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/CaseDeletionIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/TestDataProvider.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/utils/DocumentRemoteDeletionVerifier.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/utils/LauRemoteDeletionVerifier.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/utils/RemoteDeletionVerifier.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/utils/RoleRemoteDeletionVerifier.java
  src/main/java/uk/gov/hmcts/reform/ccd/data/model/CaseData.java
  src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionService.java
  src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeDocumentsRemoteOperation.java
  src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeElasticsearchRemoteOperation.java
  src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeRemoteOperation.java
  src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeRoleAssignmentsRemoteOperation.java
  src/main/java/uk/gov/hmcts/reform/ccd/service/remote/RemoteDisposeService.java
  src/test/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeDocumentsRemoteOperationTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeElasticsearchRemoteOperationTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeRoleAssignmentsRemoteOperationTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/service/remote/RemoteDisposeServiceTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-156

#158 LAU-541 update nightly build cron.
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-158

#159 LAU-541: Update nightly schedule.
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-159

#160 LAU-569: Update ppstgresql.
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-160
