Repository hmcts/ccd-case-disposer, pull requests merged in 2022-05, with the labels that each got.

#40 Lau 292
  Jenkinsfile_CNP
  build.gradle
  charts/ccd-case-disposer/Chart.yaml
  charts/ccd-case-disposer/values.preview.template.yaml
  charts/ccd-case-disposer/values.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/TestDataProvider.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/config/AuthClientsConfiguration.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/helper/GlobalSearchIndexCreator.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/helper/SecurityUtils.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/parameter/TestParameterResolver.java
  src/functionalTest/resources/application-functional.yaml
  src/functionalTest/resources/scenarios/S-022-global-search.sql
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/ApplicationBootstrapIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/ccd/data/es/CaseDataElasticsearchOperations.java
  src/main/java/uk/gov/hmcts/reform/ccd/parameter/DefaultParameterResolver.java
  src/main/java/uk/gov/hmcts/reform/ccd/parameter/ParameterResolver.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/ccd/data/es/CaseDataElasticsearchOperationsTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-40

#41 try using change id from env vars
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-41

#42 use env.BRANCH_NAME
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-42

#43 disable build-breaking line
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-43

#33 LAU-325: Add Staging DB for Functional Tests
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-33

#45 LAU-325: Removing deployment_namespace var
  infrastructure/variables.tf
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-45

#52 CCD 3096 Update 'spring-framework.version' to '5.3.19' and removal of suppression CVE-2022-22968
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-52

#56 suppression of CVE-2016-1000027 and until date extension for current …
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-56

#59 CVE-2016-1000027 is noted as false positive
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-59

#60 CCD-3294: Removed suppression and updated spring-framework.version to 5.3.20
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-60
