Repository hmcts/ccd-case-disposer, pull requests merged in 2022-12, with the labels that each got.

#161 CCD-4043 Fasterxml Jackson Upgrade
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-161

#163 LAU-575 Suppressing CVE
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-163

#162 LAU-555: Updated workflow actions.
  .github/workflows/ci.yml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-162
