Repository hmcts/ccd-case-disposer, pull requests merged in 2023-06, with the labels that each got.

#254 LAU-668 j-text-utils dependency suppression
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-254

#264 LAU-681 suppress CVE-2023-35116
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-264

#266 Fix app insights connection string
  lib/applicationinsights.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-266
