Repository hmcts/ccd-case-disposer, pull requests merged in 2023-02, with the labels that each got.

#175 Lau 597
  charts/ccd-case-disposer/Chart.yaml
  charts/ccd-case-disposer/values.preview.template.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/CaseDeletionFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/utils/DocumentDeleteTestUtils.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/utils/ElasticSearchTestUtils.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/utils/LauTestUtils.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/utils/RoleDeleteTestUtils.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-175

#174 CCD-4267
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-174

#178 LAU-604 configuring dependabot newer version
  .dependabot/config.yml
  .github/dependabot.yml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-178

#185 Upgrade java to v17
  .github/workflows/ci.yml
  Dockerfile
  acb.tpl.yaml
  build.gradle
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/config/es/ElasticSearchIndexCreator.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-185

#192 Suppress CVE-2022-45688 as project does not contain json-java or hutool
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-192
