Repository hmcts/ccd-case-disposer, pull requests merged in 2023-05, with the labels that each got.

#237 LAU-649 bump spring security version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-237

#246 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-246

#251 LAU-612 bump gradle to version 8
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-251
