Repository hmcts/ccd-case-disposer, pull requests merged in 2023-09, with the labels that each got.

#291 LAU-726 new renovate config
  .github/renovate.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-291

#207 Lau task deletion
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/ccd-case-disposer/Chart.yaml
  charts/ccd-case-disposer/values.preview.template.yaml
  charts/ccd-case-disposer/values.yaml
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/CaseDeletionFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/TestDataProvider.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/data/DeletionScenarios.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/parameter/TestParameterResolver.java
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/utils/TaskDeleteTestUtils.java
  src/functionalTest/resources/application-functional.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/config/TestParameterResolver.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/config/WireMockStubs.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/constants/TestConstants.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/utils/TasksRemoteDeletionVerifier.java
  src/integrationTest/resources/application-test.yaml
  src/main/java/uk/gov/hmcts/reform/ccd/data/tm/DeleteCaseTasksAction.java
  src/main/java/uk/gov/hmcts/reform/ccd/data/tm/DeleteTasksRequest.java
  src/main/java/uk/gov/hmcts/reform/ccd/parameter/DefaultParameterResolver.java
  src/main/java/uk/gov/hmcts/reform/ccd/parameter/ParameterResolver.java
  src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeTasksRemoteOperation.java
  src/main/java/uk/gov/hmcts/reform/ccd/util/RestConstants.java
  src/main/java/uk/gov/hmcts/reform/ccd/util/log/TasksDeletionRecordHolder.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/ccd/parameter/DefaultParameterResolverTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeTaskRemoteOperationTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/util/log/TaskDeleteRecordHolderTest.java
Labels: ns:ccd, prd:ccd, keep-helm, rel:ccd-case-disposer-pr-207

#310 LAU-678 log 1% of health messages
  lib/applicationinsights.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-310

#323 LAU-747 remove removed jenkins actions from Jenkinsfile
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-323
