Repository hmcts/ccd-case-disposer, pull requests merged in 2023-03, with the labels that each got.

#202 LAU-611 Dependabot configuration
  .github/dependabot.yml
  build.gradle
  charts/ccd-case-disposer/Chart.yaml
  charts/ccd-case-disposer/values.preview.template.yaml
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, keep-helm, rel:ccd-case-disposer-pr-202

#203 LAU-603 changing .internal for elastic search
  Jenkinsfile_CNP
  bin/load-preview-environment-variables.sh
  charts/ccd-case-disposer/values.preview.template.yaml
Labels: ns:ccd, prd:ccd, keep-helm, rel:ccd-case-disposer-pr-203

#206 Remove unnecessary dependency
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-206

#212 LAU-618 suppress CVE-2022-1471
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-212

#218 CCD-4454 : Fix for CVE-2022-1471
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-218

#219 CVE-2023-20861 springFramework fix
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-219
