Repository hmcts/ccd-case-disposer, pull requests merged in 2023-01, with the labels that each got.

#164 LAU-584 suppressing CVE
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-164

#165 LAU-586 suppressing CVE
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-165

#166 LAU-571 logstash version upgrade
  charts/ccd-case-disposer/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-166

#170 LAU-527 Update to fix helm uninstall not firing in build
  Jenkinsfile_CNP
  charts/ccd-case-disposer/Chart.yaml
  charts/ccd-case-disposer/values.preview.template.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-170

#172 Update onswap version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-172
