Repository hmcts/ccd-case-disposer, pull requests merged in 2024-01, with the labels that each got.

#424 LAU-831 upgrade charts-job to latest
  charts/ccd-case-disposer/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-424

#437 LAU-834 fix image pull failures on jenkins
  acb.tpl.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-437

#436 Remove explicit setting of pitest version and use what plugin provides
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-436

#438 LAU-834 add retries to missed blocks
  acb.tpl.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-disposer-pr-438
